version: '3.7'
services:
  kratos-migrate:
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./minos-configs
        target: /etc/config/kratos
    entrypoint: /bin/sh -c "/usr/bin/kratos -c /etc/config/kratos/kratos.yml migrate sql -e --yes >/dev/null 2>&1"
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.13.0
    env_file:
      - .env
    environment:
    - COURIER_SMTP_CONNECTION_URI
    - SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS_0_CONFIG_AUTH_CONFIG_VALUE
    - SELFSERVICE_FLOWS_REGISTRATION_AFTER_OIDC_HOOKS_0_CONFIG_AUTH_CONFIG_VALUE
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_1_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_1_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_2_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_2_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_4_APPLE_PRIVATE_KEY_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_4_APPLE_PRIVATE_KEY
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_4_TEAM_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_5_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_5_CLIENT_SECRET
    - SECRETS_COOKIE
    - SECRETS_CIPHER
    - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    - LOG_LEVEL=trace
    ports:
      - '4433:4433' # public
      # - '4434:4434' # admin. can be uncommented for testing- but should be removed in prod.
    restart: unless-stopped
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./minos-configs
        target: /etc/config/kratos
  minos:
    build: minos
    ports:
      - "4000:4000"
    env_file:
      - minos/.env

volumes:
  kratos-sqlite:
