version: '3.7'
services:
  kratos-migrate:
    image: oryd/kratos:v0.11.1
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./minos-configs
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.11.1
    env_file:
      - .env
    environment:
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_1_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_1_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_2_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_2_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_4_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_4_CLIENT_SECRET
    - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    - LOG_LEVEL=trace
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./minos-configs
        target: /etc/config/kratos
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
  pasiphae:
    build:
      context: nuxt-3-example
    ports: 
      - "4455:4455"
      - "24678:24678"
      - "24679:24679"
  #### Comment the 'pasiphae' block, and uncomment this, to use default Ory UI
  # kratos-selfservice-ui-node:
  #   image: oryd/kratos-selfservice-ui-node:v0.11.1
  #   ports:
  #     - "4455:4455"
  #   environment:
  #     - PORT=4455
  #     - SECURITY_MODE=
  #     - KRATOS_PUBLIC_URL=http://kratos:4433/
  #     - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
  #   restart: on-failure

  minos: 
    build: minos
    ports: 
      - "4000:4000"
volumes:
  kratos-sqlite:
