version: '3.7'
services:
  kratos-migrate:
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=${DATABASE_URL}
    entrypoint: /bin/sh -c "/usr/bin/kratos -c /etc/config/kratos/${KRATOS_YML} migrate sql -e --yes >/dev/null 2>&1"
    restart: on-failure
    volumes:
      - config-data:/etc/config/kratos

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.13.0
    env_file:
      - .env
    environment:
    - COURIER_SMTP_CONNECTION_URI
    - SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS_0_CONFIG_AUTH_CONFIG_VALUE
    - SELFSERVICE_FLOWS_REGISTRATION_AFTER_OIDC_HOOKS_0_CONFIG_AUTH_CONFIG_VALUE
    - SELFSERVICE_FLOWS_SETTINGS_AFTER_HOOKS_0_CONFIG_URL
    - SELFSERVICE_FLOWS_SETTINGS_AFTER_HOOKS_0_CONFIG_AUTH_CONFIG_VALUE
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_1_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_1_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_2_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_2_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_CLIENT_SECRET
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_4_APPLE_PRIVATE_KEY_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_4_APPLE_PRIVATE_KEY
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_4_TEAM_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_5_CLIENT_ID
    - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_5_CLIENT_SECRET
    - SECRETS_COOKIE
    - SECRETS_CIPHER
    - DSN=${DATABASE_URL}
    - LOG_LEVEL
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin. can be uncommented for testing- but should be removed in prod.
    restart: unless-stopped
    command: serve -c /etc/config/kratos/${KRATOS_YML} --dev --watch-courier
    volumes:
      - config-data:/etc/config/kratos
        
  minos:
    build: minos
    # image: ghcr.io/modrinth/minos:staging
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment: 
    - ORY_AUTH_BEARER
    - SENTRY_DSN
  pasiphae:
    build: pasiphae
    # image: ghcr.io/modrinth/pasiphae:staging
    depends_on:
      - kratos
    env_file:
      - .env
    ports:
      - "4455:4455"
    volumes:
      - config-data:/etc/config/kratos

  # kratos-selfservice-ui-node:
  #   image: oryd/kratos-selfservice-ui-node:v0.13.0
  #   ports:
  #   - "4455:4455"
  #   environment:
  #     - PORT=4455
  #     - SECURITY_MODE=
  #     - KRATOS_PUBLIC_URL=http://kratos:4433
  #     - KRATOS_BROWSER_URL=http://kratos:4433

volumes:
  config-data:
